import { z } from "zod";

export const ERROR_CODES = {
  AUTH_CSRF_INVALID: "AUTH_CSRF_INVALID",
  AUTH_FORBIDDEN: "AUTH_FORBIDDEN",
  AUTH_REQUIRED: "AUTH_REQUIRED",
  CHAIN_CONFIG_INVALID: "CHAIN_CONFIG_INVALID",
  CHAIN_TRANSACTION_NOT_FOUND: "CHAIN_TRANSACTION_NOT_FOUND",
  CHAIN_TRANSACTION_REVERTED: "CHAIN_TRANSACTION_REVERTED",
  CHAIN_TRANSACTION_UNKNOWN: "CHAIN_TRANSACTION_UNKNOWN",
  CHAIN_UNSUPPORTED: "CHAIN_UNSUPPORTED",
  EVIDENCE_HASH_MISMATCH: "EVIDENCE_HASH_MISMATCH",
  EVIDENCE_DUPLICATE_CHECK: "EVIDENCE_DUPLICATE_CHECK",
  EVIDENCE_NOT_PASSING: "EVIDENCE_NOT_PASSING",
  EVIDENCE_REQUIRED_CHECK_MISSING: "EVIDENCE_REQUIRED_CHECK_MISSING",
  EVIDENCE_RESIDUAL_SECRET: "EVIDENCE_RESIDUAL_SECRET",
  GIT_COMMIT_MISMATCH: "GIT_COMMIT_MISMATCH",
  GIT_DIRTY: "GIT_DIRTY",
  IDEMPOTENCY_CONFLICT: "IDEMPOTENCY_CONFLICT",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  INVALID_CONTENT_TYPE: "INVALID_CONTENT_TYPE",
  INVALID_STATE: "INVALID_STATE",
  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
  POLICY_INVALID: "POLICY_INVALID",
  POLICY_NOT_FOUND: "POLICY_NOT_FOUND",
  POLICY_PATH_OUTSIDE_REPOSITORY: "POLICY_PATH_OUTSIDE_REPOSITORY",
  POLICY_UNSAFE_COMMAND: "POLICY_UNSAFE_COMMAND",
  POLICY_ALREADY_EXISTS: "POLICY_ALREADY_EXISTS",
  PROJECT_SLUG_CONFLICT: "PROJECT_SLUG_CONFLICT",
  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
  RATE_LIMITED: "RATE_LIMITED",
  RECEIPT_NOT_FOUND: "RECEIPT_NOT_FOUND",
  TASK_NOT_FOUND: "TASK_NOT_FOUND",
  TOKEN_REVOKED: "TOKEN_REVOKED",
  VALIDATION_INVALID_INPUT: "VALIDATION_INVALID_INPUT",
  VALIDATION_UNSUPPORTED_SCHEMA: "VALIDATION_UNSUPPORTED_SCHEMA"
} as const;

export const ErrorCodeSchema = z.enum(Object.values(ERROR_CODES));

export const ApiErrorSchema = z.strictObject({
  error: z.strictObject({
    code: ErrorCodeSchema,
    message: z.string().min(1).max(500),
    correlationId: z.string().min(1).max(128),
    retryable: z.boolean(),
    fieldErrors: z
      .array(
        z.strictObject({
          path: z.string().min(1).max(512),
          code: z.string().min(1).max(128)
        })
      )
      .max(100)
      .optional()
  })
});

export type ErrorCode = z.infer<typeof ErrorCodeSchema>;
export type ApiError = z.infer<typeof ApiErrorSchema>;
